### ISSUE TITLE
Edit link missing from Actions column

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#100]
The actions column on the products list needs to include an `Edit` link. The product title is linked to the edit screen but not having an edit link as well is less intuitive.
<img width="860" alt="screen shot 2017-10-19 at 9 40 46 pm" src="https://user-images.githubusercontent.com/1034109/31802894-504e2528-b516-11e7-8a7a-7027d23eb546.png">

**Comment by DrewAPicture** [comment]
As discussed in Slack yesterday, if we add it back we'll need to fix the line-wrap that happens when there are more than two links in that column.

**Comment by pippinsplugins** [comment]
Let's fix the line wrap then. I'd definitely like there to be an edit link unless there's a really good reason for why not to have one.

**Comment by amdrew** [comment]
There won't be any line wrapping with the new UI, I think we can hold out with a wrapped link for now
