### ISSUE TITLE
Products: Remove sellbird prefixes from most HTML attributes

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#108]
From Slack:
> Thoughts on removing the "sellbird-" prefix on ids and classes in use in our markup?
> I think we get so used to having to play nice with other vendors that we end up kind of being too verbose. Not to mention, it significantly lengthens said attributes.
>
> In the case of stuff we fully control, I think we can pretty safely skip the prefixing.
> I just see this kind of stuff and it makes it really hard to grok'
>
> ![Code](https://cl.ly/3V3v0B2b1j1x/Screen%20Shot%202017-11-01%20at%201.21.20%20AM.png)

**Comment by DrewAPicture** [comment]
Attaching this to the checklist for #44.

**Comment by DrewAPicture** [comment]
PR in progress: #109

**Comment by pippinsplugins** [comment]
:+1:
