### ISSUE TITLE
Option to delete products

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#11]
We need to allow store owners to delete products.

Deleting a product should not remove orders or customers.

Moved from https://github.com/SellBirdHQ/sellbird/issues/8

**Comment by DrewAPicture** [comment]
PR: #50 adds a deletion workflow for single products.

Adds:
* A `/products/delete/###` rewrite (so make sure to run `wp rewrite flush` before testing)
* An AYS (are you sure?) template giving the option to proceed with the deletion or cancel (both redirect back to the main products list)
* Adjusts `Util\Products::status()` to accept an optional product ID so it can be used outside The Loop
* Adds a "Delete" link to the Actions column in the products list

Screenshots:
**Actions:**
![Actions](https://cl.ly/1g3f0Z2L2o20/Screen%20Shot%202017-09-11%20at%203.00.25%20PM.png)

**AYS:**
![AYS](https://cl.ly/2t0d352d3i1O/Screen%20Shot%202017-09-11%20at%203.00.57%20PM.png)

**Comment by DrewAPicture** [comment]
78b05e17f00756052e81d1f927194c27bc2e1a6d also adds a product delete link to the edit template:

![Delete From Edit](https://cl.ly/0b1A2d3N2E0k/Screen%20Shot%202017-09-11%20at%203.05.19%20PM.png)

**Comment by pippinsplugins** [comment]
PR looks great!
