### ISSUE TITLE
PHP Warning:  strpos() expects parameter 1 to be string

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#111]
When adding a product I get the following immediately after clicking `Add Product`:

```
PHP Warning:  strpos() expects parameter 1 to be string, array given in /wp-content/plugins/easy-digital-downloads/includes/formatting.php on line 38
```

Last lines in stack trace

```
edd_sanitize_amount() /wp-content/themes/sellbird/includes/dashboard/products/class-save.php:75
PHP  11. strpos() /wp-content/plugins/easy-digital-downloads/includes/formatting.php:38
```

The product is still added successfully.

**Comment by DrewAPicture** [comment]
OK, I'll look into it.

**Comment by DrewAPicture** [comment]
@amdrew This may have been inadvertently mitigated as part of #44. Can you see if you can get it to happen again please? :-)

**Comment by DrewAPicture** [comment]
Unable to reproduce. Please re-open if it pops up again.
