### ISSUE TITLE
Order filters

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#12]
The filters on the Orders tab of the dashboard need to be made functional.

Previously: https://github.com/SellBirdHQ/sellbird/issues/9

**Comment by DrewAPicture** [comment]
See #126 for where a (hidden) `customer_id` filter is being added.

**Comment by DrewAPicture** [comment]
PR with working order filters: #227

**Comment by DrewAPicture** [comment]
@amdrew Can you please test? I've fixed the merge conflict in the PR.

**Comment by amdrew** [comment]
@DrewAPicture Works well in my testing for email addresses and date ranges.

Let's add a way to clear the filter and reset back to the default view. Unless you have a better idea, how about a `Reset search` link somewhere near the top?

**Comment by DrewAPicture** [comment]
> Let's add a way to clear the filter and reset back to the default view. Unless you have a better idea, how about a Reset search link somewhere near the top?

I think there's two parts to this actually:

1. I'd like there to be some indication – whether the filter drawer is expanded or not – that filters are applied even if we don't list what they are.
2. Then maybe adjacent to the indication that filters are applied we just put an X or something to clear the filters. Lots of different UIs do this in different ways.

Either way, let's merge this and start a new issue for that.

**Comment by DrewAPicture** [comment]
Opened #245.
