### ISSUE TITLE
Load datepicker so we can create date-driven fields in templates

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#121]
Related: #114, #84 

We've already implemented some "date" type fields using the `HTML` class, we should probably make them actually act like date fields!

**Comment by amdrew** [comment]
The `date` input field isn't supported in Safari (desktop) so we'll need to complete this for 1.0.

https://caniuse.com/#feat=input-datetime

View this link in Safari (I'm using 11.0.3 on mac) and you'll see no pop up when you focus on the field
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date

**Comment by DrewAPicture** [comment]
This is done as of #197. All "date" fields have been converted to standard text inputs and globally have datepickers instantiated against them if they have the `sellbird-date` class.
