### ISSUE TITLE
Post status drop down includes All and None values

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#124]
`All` and `None` should not be included:
![image](https://user-images.githubusercontent.com/1034109/33586907-52d4ae04-d931-11e7-8632-1d05b2a8f758.png)

**Comment by amdrew** [comment]
We should also change `Publish` to `Live` so it's consistent with the `status` on the main products screen.

**Comment by amdrew** [comment]
@SellBirdHQ/core Ready for testing: https://github.com/SellBirdHQ/theme/pull/177

**Comment by pippinsplugins** [comment]
Looks good, merged.
