### ISSUE TITLE
New menu proposal

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#127]
The current menu:

- Home
- Products
- Customers
- Orders
- Settings
- Managers
- Billing

I don't think `Managers` and `Billing` should exist in this menu. For the purposes of launch however, they can stay where they are for the time being. The menu IMO should be made up of menu items that are accessed frequently, and ordered accordingly. Billing isn't something we want to remind end-users of while they are managing their store. 

I see `Managers` and `Billing` as more of sub items under settings. `Settings` also isn't a menu item that will be accessed frequently, so I propose we move it to the bottom of the sidebar, or under the profile. Or it can stay where it is for now. 

The proposed menu:

- Home
- Orders (an end-user will hopefully be more orders than products, so this is more important)
- Products
- Customers
- Managers (can stay for now, but could move to `Settings` in the future)
- Billing (can stay for now, but could move to `Settings` in the future)
- Settings (can stay for now, or moved to the bottom of the UI in the sidebar, or somewhere in the top, perhaps under the profile link)

**Comment by pippinsplugins** [comment]
I think `Settings` should become it's own section within the menu (near the bottom). It can then contain:

- Profile
- Billing
- Managers
- Notifications

An any future settings.

**Comment by amdrew** [comment]
Yep

**Comment by amdrew** [comment]
I've updated the menu order for now.

**Comment by amdrew** [comment]
The settings page now contains Managers, General Settings, Profile, and Billing. The naming/design isn't finalized but here's what we have so far:

<img width="1530" alt="screen shot 2018-04-12 at 4 45 05 pm" src="https://user-images.githubusercontent.com/52581/38656799-e553d5ee-3e70-11e8-9d3c-f62d785ff3b1.png">

Billing and Managers have been dropped from the main menu and the profile link now points to the profile section inside settings.

Routes have been updated so they are `settings/general`, `settings/managers`, `settings/managers/add` and so forth.

**Comment by amdrew** [comment]
First attempt at a breadcrumb menu to help navigate:

<img width="398" alt="screen shot 2018-04-13 at 11 41 30 am" src="https://user-images.githubusercontent.com/52581/38709544-b6d8f286-3f0f-11e8-967b-4a415b8cddbc.png">

<img width="389" alt="screen shot 2018-04-13 at 11 41 42 am" src="https://user-images.githubusercontent.com/52581/38709543-b6a48258-3f0f-11e8-9dd2-6519fdb592f3.png">

**Comment by DrewAPicture** [comment]
Per the scrub discussion yesterday, @amdrew is continuing forward with this.

**Comment by amdrew** [comment]
Added some buttons:

<img width="1346" alt="screen shot 2018-06-18 at 1 37 02 pm" src="https://user-images.githubusercontent.com/52581/41514636-b91970f4-72fc-11e8-9c28-4781105001aa.png">

**Comment by amdrew** [comment]
I'll calling this done. I've added some temporary descriptions. After we know for sure what each screen contains we can spruce up the copy.

Here's some final screens at different browser widths:

<img width="1775" alt="screen shot 2018-06-18 at 2 38 00 pm" src="https://user-images.githubusercontent.com/52581/41515816-4a448228-7305-11e8-854d-78063cbba281.png">
<img width="1311" alt="screen shot 2018-06-18 at 2 37 57 pm" src="https://user-images.githubusercontent.com/52581/41515818-4a7007e0-7305-11e8-8ca0-57c2bb1f00a1.png">
<img width="1080" alt="screen shot 2018-06-18 at 2 37 50 pm" src="https://user-images.githubusercontent.com/52581/41515820-4a9ba47c-7305-11e8-9492-2aaf1fe21cef.png">
<img width="447" alt="screen shot 2018-06-18 at 2 37 37 pm" src="https://user-images.githubusercontent.com/52581/41515822-4ac6cada-7305-11e8-955b-e5c4366475da.png">
