### ISSUE TITLE
Products cannot be deleted

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#131]
Products cannot be deleted. When you confirm the deletion, it reloads the products page with the product still in the list (I tested this before the new UI changes and it was the same).

**Comment by DrewAPicture** [comment]
My objections stand on being able to actually delete products vs deactivate them or mark them discontinued or something.

**Comment by pippinsplugins** [comment]
I think we should move them to the trash but not (at least for now) allow store owners to un-trash products. By having them in the trash, they are accessible by site admins in the case a store owner asks for help int restoring a deleted product.

**Comment by amdrew** [comment]
The issue of a product not being able to be deleted seems to have fixed itself.

PR for the comment above:. A product will now go to the trash instead of being permanently deleted: https://github.com/SellBirdHQ/theme/pull/179

Interestingly, `wp_delete_post` should have made a product go to trash, since force deletion is false by default. Somehow that's not working. I wonder if it's somehow related to multisite and the `switch_to_store()` and `restore_main_site()` functions. `wp_trash_post()` seems to work fine in my testing, though that just calls `wp_delete_post` anyway I believe, shrug.

https://codex.wordpress.org/Function_Reference/wp_delete_post
