### ISSUE TITLE
Change "price" input field to have a type of "text"

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#134]
The `Price` input field on product screens has an input type of `number`. I propose we change this to `text`. 

For some currencies, incrementing by `1` doesn't really help. Also, prices like `2.50` etc are quite common.

**Comment by DrewAPicture** [comment]
I've been investigating how we could generally improve this. I agree that the number field dropping trailing zeroes is super annoying. One solution that I _really_ dig is the "Currency without spinbuttons with bootstrap" option that you can demo [here](http://jsfiddle.net/trixta/UC6tG/).

Looks like this:

![Formatted currency](https://cl.ly/233Q2N1X0y37/Screen%20Shot%202018-05-24%20at%202.07.44%20PM.png)

In Bootstrap 4, the currency symbol appended to the beginning is accomplished with the `.input-group-prepend` and `.input-group-text` classes on the control inside a `.input-group` wrapper.

The thousands and decimal separators are handled via webshims which isn't compatible with jQuery 3.x, but WP is still on 1.x with jquery-migrate anyway so I'm not sure that particularly matters.

Either way, I think we just flip it to `type=text` and put an integer validator on it with Parsley, but I'd ultimately like to work toward something similar to what's described above.

**Comment by DrewAPicture** [comment]
Worth noting that once we're supporting multiple currencies, rather, supporting one currency with multiple choices, implementing support for the different currency symbols and rules is trivial.

**Comment by DrewAPicture** [comment]
So what we're going to do here for now is change to a text field and use Parsley to validate it as an integer.

**Comment by DrewAPicture** [comment]
With the attached PR, the price field now saves the prices with the trailing zero. This is partially accomplished by supplying a RegEx to the input that makes it possible to enter ##,  ##.# or ##.##. All will be treated equally, however.
