### ISSUE TITLE
Can't add price if no product price is originally entered

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#136]
If you add a product without a price, the `Add New Price` button shows on the following edit screen, however when you click it, nothing happens. This issue is also present before the recent UI updates.

It seems a good solution would to simply introduce required fields. Or even fallback to `0.00` if no price is entered.

**Comment by DrewAPicture** [comment]
This has been resolved via #211 for #203 with the introduction of form validation with Parsley.
