### ISSUE TITLE
"Set as default" not working correctly when adding a new product

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#138]
When adding a new product and also adding multiple prices, the `Set as default` radio input doesn't work as intended. When you click to set another price option as the default, it doesn't move the previous selection and you end up with everything being default.

<img width="504" alt="screenshot 2017-12-05 16 35 28" src="https://user-images.githubusercontent.com/52581/33588923-54169ef4-d9da-11e7-98a6-44af2ed64c13.png">

**Comment by DrewAPicture** [comment]
This was fixed awhile ago.
