### ISSUE TITLE
Order details screen

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#14]
We need a screen that shows the complete details of an individual order.

Previously: https://github.com/SellBirdHQ/sellbird/issues/12

**Comment by pippinsplugins** [comment]
I'd like the following information to be shown:

- Order ID
- Order date and time
- Customer name
- Customer email
- Total amount
- Discount amount
- Tax amount
- Subtotal (before tax, before discounts)
- Product(s) ordered
- Billing address, if present (maybe)
- IP address (maybe)

**Comment by DrewAPicture** [comment]
Started a rough PR: #64

**Comment by DrewAPicture** [comment]
@pippinsplugins This is ready for review. I decided to keep the output simple until @amdrew has a chance to come through and beautify it later. Couple things to note:

* I've added pseudo payment ID (payment_number) support so that we can link to the payment numbers in `orders/##` instead of the _actual_ payment ID from the post object. I feel like this will ultimately reduce confusion and allow us to remain consistent in the order "IDs" that we display everywhere front-facing
* I fixed the display label for statuses in the Orders list to show the `status_nicename` instead of the actual post status
* How the customer address is parsed for display is a little janky, but I couldn't find a better example in EDD core for how to accomplish that
* Similarly, you might have a better idea for querying the list of products for display. I imagine you might even want to link to the product edit URLs, and if so, that's easy enough to do

Currently looks like this (again, intentionally pretty basic on the display front:
![Order details](https://cl.ly/2O1o0r0f1m1W/Screen%20Shot%202017-09-30%20at%202.17.28%20PM.png)

**Comment by DrewAPicture** [comment]
Opened #65 for styling this template.

**Comment by pippinsplugins** [comment]
EDD core displays the products purchased in an unordered list, that way it can handle 1-100 products per order.

Unless @amdrew disagrees, I think we should go ahead and put ordered items in a UL. Each item also needs to have a price displayed with it so that customers can see the individual item prices.

**Comment by amdrew** [comment]
UL is great

**Comment by DrewAPicture** [comment]
Added products output as an unordered list and merged #64. Starting a new PR for adding detailed order information.

@pippinsplugins Would you mind listing out exactly what we talked about on the call in terms of detailed order information you'd like to see on this screen on top of what's there now?

**Comment by pippinsplugins** [comment]
The only thing missing is the break down of amounts for each product in the order. Each product needs to include the following:

- Subtotal
- Discount
- Tax
- Total

**Comment by DrewAPicture** [comment]
Added a new PR that covers the detailed information requested above: #80 

Looks like this:

![Product table](https://cl.ly/2W2l3t0M1X2n/Screen%20Shot%202017-10-11%20at%205.30.38%20PM.png)

**Comment by DrewAPicture** [comment]
#80 was merged.
