### ISSUE TITLE
Remove "Set as default" and "remove" link when adding a new product

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#142]
Following on from the discussion at https://github.com/SellBirdHQ/theme/issues/137, I think the `Set as default` and the `remove` link on a new product page should not be shown by default. They should only show once you have added a new price. Only then you should see options to set a price as default, or remove a price option.

1. The first price is always the default unless a new one is added, so there's no need for a "set as default" radio input
2. Clicking the "remove" link doesn't actually remove the price option so no point having a link that doesn't do anything (plus you shouldn't be able to remove the first price).

<img width="806" alt="screenshot 2017-12-06 09 55 43" src="https://user-images.githubusercontent.com/52581/33630284-a3d39258-da6b-11e7-9672-d721427141af.png">

**Comment by DrewAPicture** [comment]
You're right on both points. And also we _can't_ remove the first price because we need it to enable cloning. There's logic in the JS that actually prevents the first price from being removed.

**Comment by amdrew** [comment]
Yep 👍

**Comment by DrewAPicture** [comment]
This won't be able to proceed without #213 since we'll need it to be able to "hide" the buttons.
