### ISSUE TITLE
Improve search filter UI

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#145]
Not sure how yet, but it would be nice to condense the customer search UI which takes up a bit of room. Maybe even hide it somehow until it needs to be used.

<img width="1090" alt="screenshot 2017-12-06 10 24 32" src="https://user-images.githubusercontent.com/52581/33631523-ab453772-da6f-11e7-9696-d0d48c8138de.png">

This issue also applies to filters shown on the orders screen.

**Comment by DrewAPicture** [comment]
I imagine the customer search falls into the category of "filters", which is something we're going to need to address for use on several other screens too. Maybe a collapsible panel?

**Comment by amdrew** [comment]
Yeah, I like that.

**Comment by pippinsplugins** [comment]
I like the idea of a collapsible panel.

**Comment by amdrew** [comment]
This is what I have so far. I've removed the filters and card from above the main card, and placed the filters inside the existing card. Clicking the search link shows the filters and changes the link text. Clicking again puts it back to normal. I think this will do for now.

<img width="933" alt="screenshot 2017-12-21 18 08 39" src="https://user-images.githubusercontent.com/52581/34241390-04d82fae-e67a-11e7-9f14-499304bb8222.png">

<img width="964" alt="screenshot 2017-12-21 18 08 45" src="https://user-images.githubusercontent.com/52581/34241394-09dcd5c2-e67a-11e7-85f7-c8a7c8689db7.png">

Like the product edit screen, I'm envisioning more links being added in the future. Perhaps links to either export or import customers.

**Comment by amdrew** [comment]
PR: https://github.com/SellBirdHQ/theme/pull/163

@SellBirdHQ/core Anyone want to play? Otherwise will just merge :D

**Comment by pippinsplugins** [comment]
@amdrew that looks good! Can we change the date placeholders to `yyyy / mm / dd`?

**Comment by amdrew** [comment]
@pippinsplugins I'm not actually sure we can, at least not without implementing some JS. As far as I can see, the date input field type doesn't allow you to specify the format, and all browsers show the date field differently (styling and also format).

JS seems like the better solution here, to a) Get the format how we want and b) provide a consistent experience in terms of styling.

@DrewAPicture agree/disagree?

**Comment by pippinsplugins** [comment]
I vote we leverage the jQuery UI datepicker.

**Comment by amdrew** [comment]
Sounds good to me

**Comment by DrewAPicture** [comment]
We should definitely use the datepicker here. We can dictate the format just the same as we already do in AffWP, for instance, though I would disagree on YYYYMMDD, that feels unnatural to me.

**Comment by DrewAPicture** [comment]
See #121 for where we planned to add datepicker.

**Comment by DrewAPicture** [comment]
Left some comments on the PR. Looks like a solid start 👍

**Comment by amdrew** [comment]
@DrewAPicture Ta, all fixed, left a comment about a fatal error

**Comment by amdrew** [comment]
The filters have been tweaked ever so slightly but more or less look the same as they were before. To test, use the PR linked from https://github.com/SellBirdHQ/theme/issues/184.
