### ISSUE TITLE
Style "Replace" button

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#146]
The `Replace` button needs some styling when adding an image to an existing product.

<img width="406" alt="screenshot 2017-12-06 11 40 35" src="https://user-images.githubusercontent.com/52581/33634789-546e870e-da7a-11e7-8c56-7481a3979c67.png">

I might change this button to look more like a link (but keep it as a button). We don't want to go overboard with too many buttons on a single page.

**Comment by DrewAPicture** [comment]
I generally agree on thinking that a lot of buttons can start to look a bit busy, but those buttons represent necessary actions and not links, that's also not really a good justification for removing them, haha.

**Comment by DrewAPicture** [comment]
So i don't know, if we start to have a lot of buttons on a screen, then maybe we should look at ways we can simplify the UI, or at least hide or show certain aspects of the UI only as needed?

**Comment by amdrew** [comment]
Yeah, all depends on what the action/task is. Too many buttons disrupts the visual hierarchy and it's really confusing. Replacing an image for example isn't a high priority action, so a simple link would suffice here. Probably for adding an image also. Same goes with adding prices and files, might take another stab at those. There's some really nice inspiration on DropBox for admin product screens.

**Comment by amdrew** [comment]
Ready for testing, use PR at https://github.com/SellBirdHQ/theme/issues/184

<img width="877" alt="screen shot 2018-04-03 at 1 09 08 pm" src="https://user-images.githubusercontent.com/52581/38223682-3ad2f9e2-3740-11e8-99e6-7ace56c25600.png">

**Comment by pippinsplugins** [comment]
Looks great!
