### ISSUE TITLE
Fix product edit screen

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#147]
The font and other styling for the editor is incorrect when editing a product (it's fine when adding a product). 

<img width="1058" alt="screenshot 2017-12-06 11 43 37" src="https://user-images.githubusercontent.com/52581/33634931-d1917188-da7a-11e7-92e9-cee6c99c1381.png">

This is due to the stylesheet I'm loading only for the editor's iframe. For some reason the conditional check is blocking it from loading, it doesn't think it's a dashboard page.

**Comment by DrewAPicture** [comment]
I think one way we can get around this is to allow passing a page ID to `is_dashboard_page()`. I'm generally uneasy about relying on WordPress to set the `$post` global when using shortcodes to display stuff.

**Comment by DrewAPicture** [comment]
Out of curiosity, what styling is missing from the editor?

**Comment by amdrew** [comment]
@DrewAPicture The font of the editor in the screenshot above should match that of the add product page. Also some colors of the editor are not being applied. Basically the stylesheet for the editor is not being loaded.

**Comment by DrewAPicture** [comment]
OK, we'll get it fixed after #157.

**Comment by amdrew** [comment]
👍 Does seem like that would help. Just noticed a JS error on the product edit screen  referencing tinymce.

Scripts on the product add screen (which works) references the correct local domain of sellbird.dev. Example:

```
<script type='text/javascript' src='https://sellbird.dev/wp-includes/js/tinymce/tinymce.min.js?ver=4607-20171116'></script>
<script type='text/javascript' src='https://sellbird.dev/wp-includes/js/tinymce/plugins/compat3x/plugin.js?ver=4607-20171116'></script>
```

However, on the product edit screen which has the JS error, some scripts reference the store site:

```
<script type='text/javascript' src='https://sumobi11.sellbird.dev/wp-includes/js/tinymce/tinymce.min.js?ver=4607-20171116'></script>
<script type='text/javascript' src='https://sumobi11.sellbird.dev/wp-includes/js/tinymce/plugins/compat3x/plugin.js?ver=4607-20171116'></script>
```

I'm going to assume this is why `editor-style.css` wasn't being correctly loaded either.

**Comment by amdrew** [comment]
The JS error and the stylesheet not loading are being caused by the call to `switch_to_store();` on the product edit template.

**Comment by DrewAPicture** [comment]
That would do it.

**Comment by amdrew** [comment]
Over to you

**Comment by DrewAPicture** [comment]
@amdrew OK, I've added a PR that adds an `editor()` control to the `HTML` class that handles the site switching to try to get the editor scripts enqueued on the main site. Please test!

PR: #162

**Comment by amdrew** [comment]
@DrewAPicture Works for me! 👍
