### ISSUE TITLE
"Replace" image button shows intermittently when adding image to existing product

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#148]
When adding an image to an already existing product for the first time, the "replace" button briefly flashes on the screen and then disappears. This is visually distracting. The "replace" button should only show when editing a product with an image already added.

**Comment by DrewAPicture** [comment]
I'm going to venture a guess that it has to do with the `screen-reader-text` class, which is used because we can't hide it with `display:none;` which makes it invisible to screen readers.

**Comment by amdrew** [comment]
PR: https://github.com/SellBirdHQ/theme/pull/183

This seems to fix this issue as well as https://github.com/SellBirdHQ/theme/issues/150. It also provides consistency with the other cards on the edit/add screens in terms.

___

No Image:

<img width="951" alt="screen shot 2018-03-05 at 4 27 54 pm" src="https://user-images.githubusercontent.com/52581/36956327-aedc0fdc-2092-11e8-91a3-848ce619a605.png">

___

There's an image, so we can replace it. When clicked, it will show the above:

<img width="952" alt="screen shot 2018-03-05 at 4 27 48 pm" src="https://user-images.githubusercontent.com/52581/36956329-af04ed30-2092-11e8-9fba-e80f8f9e3da1.png">

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by amdrew** [comment]
Sneaking something closely related into this issue.

The logo setting shows a weird blank button element when an image exists:

<img width="961" alt="screen shot 2018-03-05 at 4 38 06 pm" src="https://user-images.githubusercontent.com/52581/36956687-a1fd38d4-2094-11e8-8cec-4d95158eeceb.png">

When you click the blank button to remove the image, it still shows the file name in the file upload box:

<img width="965" alt="screen shot 2018-03-05 at 4 38 15 pm" src="https://user-images.githubusercontent.com/52581/36956744-dd07e24e-2094-11e8-8a14-2dbf4aa69985.png">

___

I've added a button "link" to the top right like the product add/edit screens:

<img width="952" alt="screen shot 2018-03-05 at 4 43 10 pm" src="https://user-images.githubusercontent.com/52581/36956729-c6f1571a-2094-11e8-9358-5363ad2e431c.png">

File input is now cleared out:

<img width="960" alt="screen shot 2018-03-05 at 4 47 47 pm" src="https://user-images.githubusercontent.com/52581/36956756-f3ec487e-2094-11e8-8c3d-55d6ac441b1c.png">

**Comment by amdrew** [comment]
The original PR on this issue has been closed. To test, use the PR linked from https://github.com/SellBirdHQ/theme/issues/184.

**Comment by amdrew** [comment]
This is fixed so closing.
