### ISSUE TITLE
Improve product screen styling

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#152]
I've spent some time over the last 2 days further improving the existing product screens. These will lend a hand to other areas of the UI for faster development and consistency.

Quick overview of some improvements:

1. Fields now have focus borders
2. Further simplified the "pricing" section
3. Further simplified the "files" section
4. Reduced visual noise (there were too many buttons)
5. Made all fields consistent and cross-browser compatible. E.g. the select menus were a different height that an input field next to it.
6. Improved overall spacing
7. Improved form CSS (not limited to just product screens, also included grid styles to re-use across the dashboard)

Still a few more tweaks I want to make, mainly to copy. Also need to improve the "image" section.

WIP of pricing section:

The add price button has been replaced with a link (but still a button element) to reduce the visual noise and moved to the top-right of the section. This allows you to click 4 times and add 4 new prices, without having to mouse your mouse down to click the next button (since it changed position). The "remove" link has been moved to the same row as the other fields and right aligned. Tested using a icon to represent the action but I think text is much clearer for now and easier to understand what clicking the link will do.

<img width="852" alt="screenshot 2017-12-08 17 01 45" src="https://user-images.githubusercontent.com/52581/33750551-96ebd3d2-dc39-11e7-9b7a-3d4fce92c5ff.png">

And at a smaller resolution:

<img width="480" alt="screenshot 2017-12-08 17 02 57" src="https://user-images.githubusercontent.com/52581/33750569-aeb885f0-dc39-11e7-98d2-729575870e1a.png">

**Comment by pippinsplugins** [comment]
That is looking excellent!

I would like to explore options for `Set as default`. Perhaps it's just me but it doesn't intuitively explain what `default` means.

Perhaps `Set as default selection`?

**Comment by DrewAPicture** [comment]
How about just "Default Price" for a label?

**Comment by DrewAPicture** [comment]
And the styling of the buttons to look like links is actually kinda bothering me. Is the intention for them to link look like links, or just for them not to look like buttons? I ask because I'm not sure I'd expect a link-looking-thing to do something on _this_ page. What if we just moved to using + and X or icons in buttons for add and remove?

**Comment by amdrew** [comment]
@DrewAPicture 

Yep, the intention is for them to _look_ like links, while still being a button for accessibility. Links do have the connotation that when clicked they will do something else, i.e. take you to another page (what we most expect) however in the context of this UI, the wording of the link is meant to help with that. Too many buttons on the same page is confusing. That's why I want to nail down the overall copy.

Example: WordPress uses links on the post edit screen for `status`, `visibility` and `publish`. Clicking each link interacts with the same page, but the "Edit" text tells us it does something on _this_ screen.

<img width="298" alt="screenshot 2017-12-12 08 52 01" src="https://user-images.githubusercontent.com/52581/33850751-c43bc06c-df19-11e7-8ae3-4b76cfd207e5.png">

___

When using an actual link, which links off to another page, they use an icon to indicate to the user they will leave the current page in a new window:

<img width="269" alt="screenshot 2017-12-12 08 49 42" src="https://user-images.githubusercontent.com/52581/33850669-7da5eac4-df19-11e7-97de-2f50e51b5c0e.png">

___

In Gutenberg's current UI they use a `button` for the links below, but the buttons look like links, which change stuff within the same UI:

<img width="281" alt="screenshot 2017-12-12 08 49 18" src="https://user-images.githubusercontent.com/52581/33850641-622eec32-df19-11e7-9a79-4e74457ecc17.png">

___

Shopify uses a button in this example that looks like a link

<img width="357" alt="screenshot 2017-12-12 08 56 30" src="https://user-images.githubusercontent.com/52581/33850992-7e48740a-df1a-11e7-9aae-0bcca775814a.png">

___

> Had you thought about just using + and - or X buttons without visible text labels?

Yep! I've explored using a `x` SVG instead of the `Remove`  links, and also tried a combination of both. Ultimately I decided that using an X icon by itself doesn't provide enough context to what it will do, and perhaps confusing to non-english speakers. More than happy to revisit this in the future. 

Consistency with other elements in the UI is also important. If we have a x icon for remove, then it makes sense to use a + icon for Add. If we remove the "Add New" text and just have the + icon, what exactly does that mean? What is being added? I think text is the safest bet for now, and since it can be translated, it will allow us to reach a much wider audience. I did add `+` next to the "Add new" which isn't consistent with the remove link, but you can't really add a `-` next to the remove links :P Consider the `+` as an experiment for now until we nail the actual wording.

**Comment by amdrew** [comment]
Changed “Set as default” to “Default price”.

**Comment by amdrew** [comment]
Merging this into master. Any additional suggestions on copy can be opened in a new issue. Opening separate issue on the image section.
