### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#154]
There are some accessibility issues that aXe (https://www.deque.com/products/axe/) has raised during a brief audit that will need to be addressed. Will go through each screen and fix accordingly.

**Comment by amdrew** [comment]
WIP PR: https://github.com/SellBirdHQ/theme/pull/168

The first thing the PR fixes is the SVG icons. aXe notified me that the SVG icons shared the same ID. Sure enough, the SVGs were being outputted into the footer many times, up to 15+ on the products listing. By being in the Template class I guess they were initialised once for every product. 

Anyhow, after chatting with @pippinsplugins, we decided to create a dedicated class for any icon related stuff.

**Comment by amdrew** [comment]
Next item to tackle:

> Elements must have sufficient color contrast

This is in relation to the green accent color used in the primary menu.

**Comment by amdrew** [comment]
Other errors so far:

> Elements should not have tabindex greater than zero

```
<a class="screen-reader-shortcut" href="#wp-toolbar" tabindex="1">Skip to toolbar</a>
```

This is coming from the WP admin bar. Not something we can fix.

> Frames must have title attribute

```
<iframe class="chartjs-hidden-iframe" tabindex="-1" style="width: 100%; display: block; border: 0px none; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>
```

This is coming from the graph on the dashboard (chartJS). Something we could potentially fix through the JS somehow (since all we output is the `canvas` in the HTML).

**Comment by amdrew** [comment]
> Form elements must have labels

Fixed in PR.

**Comment by amdrew** [comment]
Some interesting information on the tabindex error:

http://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html
https://dequeuniversity.com/rules/axe/1.1/tabindex

**Comment by DrewAPicture** [comment]
Per the scrub discussion yesterday, I think the consensus was to just close this and open new issues for specific things that arise later.
