### ISSUE TITLE
Remove reliance on shortcodes / pages in the dashboard

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#157]
As it stands now, we're leveraging certain aspects of core WordPress APIs to facilitate loading the dashboard, i.e. the template loader (mostly for template part loading), the dependencies API for assets, and now also stuff related to `WP_Query`. Wherever possible, we should _eliminate reliance on `WP_Query`_, if not only to avoid the inevitable rats nest that's introduced when combining custom rewrite  endpoints with actual pages loading actual shortcodes.

Case in point: we're already starting to experience some issues with assets not consistently being loaded because WordPress isn't recognizing dynamically-loaded pages as such. This is largely because the `$post` global is never changed between pages.

We're also seeing some unfortunate performance and DRY issues around calling functions that hit the `$post` global in bootstrap files that get instantiated on every page load. What was intended as an isolated check runs for every bootstrap file on every page load. :-/

I think the way to go here would be to introduce a dashboard route (pages) registry that we can use to handle registering rewrite endpoints, dictating query vars to register against those rewrite endpoints, as well as provide a much more performant method for determining whether we're on a "dashboard page", because each registered route will be in the registry and have a unique ID.

**Comment by DrewAPicture** [comment]
Started a PR that's very much a WIP. For instance, I wouldn't try to run it yet because there's a lot that still isn't hooked up, like the rewrites being registered, etc. I'll update where there's something to actually test.

**Comment by DrewAPicture** [comment]
OK, this is ready for the first round of testing.

To test:
1. If you already had a local SellBird testing environment, you'll want to delete all of the dashboard-related pages you created in the admin and flush rewrites `wp rewrite flush`
2. After deleting the legacy pages, if you have set up the Dashboard menu, you'll need to re-add all of the dashboard page links as Custom Links because the pages no longer exist
3. Then just check to make sure all of the top-level and sub-level pages still display as expected
4. Also check that the top-level menu items are highlighted when viewing sub-pages (Products should be highlighted when viewing Product > Add/Edit/Delete, etc.)

**Comment by amdrew** [comment]
@DrewAPicture So far so good for me, everything seems to be ok.
