### ISSUE TITLE
Simplify how the HTML class builds attributes markup for all controls

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#164]
In its current state, the HTML class builds controls with a finite list of attributes that we currently support, any others just inadvertently get skipped. This is all well and good in the near term, but as our needs grow, so does the complexity of handling more and more attribute types for any number of controls.

The attached PR does the following:

* Fixes some minor notices around undefined indexes
* Rather than rely on ever-growing `sprintf()` statements, now attributes are "collected" as they're defined and sanitized then simply imploded out of the array into a string for output
* Similarly, much of the "type" logic, such as for anything passed through `build_checkable()` or `input()` is now handled via a new `$type` property to ensure simpler dependency injection in various helper methods
* `aria-label` support has been added to several more control types
* Empty attributes will also now be removed by default (this reduces cases where we're checking for the existence of atts in JS and finding them even though they're empty). Vital atts like id, name, or options will never be removed if empty.
* The `sanitize_atts()` method has been renamed to `process_args()` to more accurately describe what's happening there: not all args are attributes, for instance
* New `attribute_to_string()` and `special_to_string()` helper methods have been added to aid in building HTML markup for a variety of attribute types

**Comment by DrewAPicture** [comment]
Seriously though. Love this:

![Simplify!](https://cl.ly/2J1l433X2e1v/Screen%20Shot%202017-12-22%20at%2010.40.05%20AM.png)

**Comment by pippinsplugins** [comment]
Lovely :)
