### ISSUE TITLE
Edit/delete managers

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#176]
Currently there's no way to edit or delete a manager after they have been added.

**Comment by DrewAPicture** [comment]
@amdrew Looks like the markup output via the 'desc' parameter in the `HTML` class isn't very well placed (probably just something we haven't run into yet).

![DESC](https://cl.ly/2k3b3g100j3S/Screen%20Shot%202018-04-29%20at%205.04.57%20PM.png)

**Comment by DrewAPicture** [comment]
I've just removed the description text 'Cannot be changed' for now.
