### ISSUE TITLE
Add Manager form needs better error handling

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#188]
If you submit the Add Manager form without valid info, you get a white screen with a bland error.
<img width="1320" alt="screen shot 2018-04-05 at 9 03 19 am" src="https://user-images.githubusercontent.com/1034109/38370698-54bd7686-38b0-11e8-8f99-a746c431fe55.png">

**Comment by DrewAPicture** [comment]
WIP PR: #200

**Comment by DrewAPicture** [comment]
Merged #200.

**Comment by DrewAPicture** [comment]
The PR also covered Manager > Edit.
