### ISSUE TITLE
Edit profile screen

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#190]
Since we will be removing the standard WP admin toolbar we should introduce a page for the user to edit their profile. This would use RCP's `[rcp_profile_editor]` shortcode. The link to the profile page can be added to the new profile menu.

**Comment by amdrew** [comment]
Looks like this so far:

<img width="659" alt="screen shot 2018-04-11 at 1 13 09 pm" src="https://user-images.githubusercontent.com/52581/38591299-1f95aad0-3d8a-11e8-94b8-c667c256e7ef.png">

**Comment by amdrew** [comment]
This will do for now. Shown is the new profile page and how to access it:

<img width="1666" alt="screen shot 2018-04-11 at 1 52 38 pm" src="https://user-images.githubusercontent.com/52581/38592340-9f10b250-3d8f-11e8-8130-ee4d6f718866.png">

**Comment by amdrew** [comment]
Success and error messages are now outputted in the expected locations with the correct HTML:

<img width="1369" alt="screen shot 2018-04-11 at 2 33 46 pm" src="https://user-images.githubusercontent.com/52581/38593429-60ed0f2c-3d95-11e8-9a58-8d017d2d0221.png">

<img width="1355" alt="screen shot 2018-04-11 at 2 33 41 pm" src="https://user-images.githubusercontent.com/52581/38593430-61180c9a-3d95-11e8-97b3-f2ec76cc6918.png">

<img width="1367" alt="screen shot 2018-04-11 at 2 33 28 pm" src="https://user-images.githubusercontent.com/52581/38593431-6145e778-3d95-11e8-900a-788a73988495.png">

**Comment by amdrew** [comment]
At mobile width(s):

<img width="447" alt="screen shot 2018-04-11 at 2 43 26 pm" src="https://user-images.githubusercontent.com/52581/38593678-be5488ba-3d96-11e8-814b-cea2a5f4c0fd.png">

**Comment by pippinsplugins** [comment]
Looks great!

**Comment by DrewAPicture** [comment]
It would be nice to avoid relying on RCP's shortcodes for forms, just like we're doing for EDD. I get doing it the easy way for the MVP, but we should definitely not get into the habit of relying on these things :-)

**Comment by DrewAPicture** [comment]
Also, let's require entering the current password to change the password.

**Comment by DrewAPicture** [comment]
This is already done.
