### ISSUE TITLE
Beautify output of the HTML->input() descriptions

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#193]
As discovered in #176, looks like the `HTML` class kind of borks both the contents and markup of the 'desc' argument for things like text inputs:

![DESC](https://cl.ly/2k3b3g100j3S/Screen%20Shot%202018-04-29%20at%205.04.57%20PM.png)

I didn't look too closely, but based on the mashed up words, I'm guessing it's trimming the contents. As for the location and styling of the description, do what you will. I would've probably expected it to output _below_ the input.

**Comment by amdrew** [comment]
Weird, will have a look. 

👍 for descriptions below the input, did this with Themedd:

<img width="759" alt="screen shot 2018-05-08 at 3 49 25 pm" src="https://user-images.githubusercontent.com/52581/39737091-767ec130-52d7-11e8-8847-7e20890117d3.png">

**Comment by amdrew** [comment]
Updated PR to include the description below the input and added the relevant CSS classes to input and textarea:

<img width="735" alt="screen shot 2018-05-08 at 4 42 03 pm" src="https://user-images.githubusercontent.com/52581/39738370-de13688a-52de-11e8-9c71-4dd63a408fda.png">
