### ISSUE TITLE
Icon for Discounts

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#198]
With Discounts now in as of the completion of #84, I think we might need an icon that :-)

![Discounts](https://cl.ly/1z3d3L3a3g0F/Screen%20Shot%202018-05-02%20at%205.48.46%20PM.png)

**Comment by amdrew** [comment]
<img width="236" alt="screen shot 2018-05-08 at 12 41 51 pm" src="https://user-images.githubusercontent.com/52581/39731702-3530b23e-52bd-11e8-8e74-5b1d32b370e4.png">
