### ISSUE TITLE
Handle product image uploads via Ajax (a la store logo)

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#20]
I've already abstracted the code in `Ajax_Actions` for programmatically uploading images, all that would be required for implementing product image upload is some JS with an Ajax callback and preview logic.

**Comment by DrewAPicture** [comment]
Started a PR: #36

**Comment by DrewAPicture** [comment]
Updating a product image:

![Preview](https://cl.ly/3B2r040w1W3A/Screen%20Recording%202017-09-02%20at%2009.03%20PM.gif)

**Comment by pippinsplugins** [comment]
Looks good!
