### ISSUE TITLE
Discounts: leaving expiration / start date blank results in date of 01/01/1970

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#205]
If you leave the expiration / start date blank, you end up with a date of `01/01/1970`.

**Comment by DrewAPicture** [comment]
This will be avoided/fixed when #202 is finished.

**Comment by DrewAPicture** [comment]
On second thought, since neither of those date fields appear to be required, we definitely need to fix the saving logic :-)

PR: #206
