### ISSUE TITLE
Only display the selectWoo search field for some drop-downs

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#220]
SelectWoo shows a search field on the select menus. It some areas of the UI, such as the status it's not needed:

<img width="901" alt="screen shot 2018-05-08 at 1 42 26 pm" src="https://user-images.githubusercontent.com/52581/39733205-ae3d3fd2-52c5-11e8-88bb-ec737c82f2b2.png">

And the discount add screen:

<img width="279" alt="screen shot 2018-05-08 at 1 48 27 pm" src="https://user-images.githubusercontent.com/52581/39733377-8db32cee-52c6-11e8-8055-9d117630f6a4.png">

<img width="750" alt="screen shot 2018-05-08 at 1 49 10 pm" src="https://user-images.githubusercontent.com/52581/39733389-9dd72288-52c6-11e8-9c48-be733ba14f47.png">

**Comment by DrewAPicture** [comment]
I updated the title to be a bit more specific to the problem. In this case, we should probably hide the search field by default via the `.select2-search` class and then re-show it based on a class set on the selects where it's actually useful.

**Comment by DrewAPicture** [comment]
@amdrew Can you take this one based on my previous comment? I've never been able to get grunt CSS tasks to run, and not sure what I'm doing wrong.

**Comment by amdrew** [comment]
@DrewAPicture Yep I can take it.

Do you see any errors of any kind when you run `grunt`? I'd also suggest running `npm update`, perhaps there's an issue with one of your packages.

**Comment by amdrew** [comment]
PR: https://github.com/SellBirdHQ/theme/pull/229

According to https://github.com/SellBirdHQ/theme/issues/196, selectWoo was implemented for use with multi-selects. The PR simply prevents selectWoo from being initialized on normal select menus, so it doesn't affect any select menu shown in the screenshots above.

**Comment by DrewAPicture** [comment]
Binding selectWoo to _all_ selects was a conscious decision. It allows for dynamically loading choice in the future which may not have much bearing right now, but I'd like us to get used to having them. So I'm gonna go with either hiding the search field if you don't want it or wontfix.

**Comment by amdrew** [comment]
Ok, let's instead hide the search field on standard (non multiple) select fields with `minimumResultsForSearch: -1`. In the future, if we decide that some selects do in fact need a search field provided by Select2/SelectWoo, we can look at conditionally toggling it search based on a class name.
