### ISSUE TITLE
Store tagline shouldn't be a required field

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#233]
It's currently required that a store owner enter a store tagline. I don't think this should be the case:

<img width="787" alt="screen shot 2018-05-24 at 2 10 21 pm" src="https://user-images.githubusercontent.com/52581/40460715-37469dbc-5f5c-11e8-8e4c-9dfd299b25f7.png">

I would actually propose we remove this setting altogether. It's something I've rarely seen on sites. If a store does have a tagline, it's usually included as part of the logo, or as part of the hero/introduction section. It seems like one of those things we're all used to adding to our themes because WordPress has had the option for so long.

@pippinsplugins @DrewAPicture What do you think?

**Comment by pippinsplugins** [comment]
I have no qualms with removing it.

**Comment by DrewAPicture** [comment]
Per the scrub discussion yesterday, we're going to go ahead and remove this. If, later, there's a demonstrated need for it to return – perhaps as a motto or slogan field – we can add it back.
