### ISSUE TITLE
Simplify registration form

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#240]
| PR | Relies On | Tracking | Project |
------ | ------------ | ----------- | ------------
| ~#246~, ~#261~ | ? | ? | [MVP](https://github.com/SellBirdHQ/theme/projects/1)

The current registration form has too many fields.

We're going to instead create a super simple form with the bare minimum fields required:

1. Email Address
2. Password
3. Store name

Note there are no payment fields. A free trial will be offered, details of which can be discussed in another issue if need be.

For the MVP, the following will need to happen during trial registration (in terms of nuts and bolts):

* [x] Create the site
* [x] Activate needed plugins (EDD) (RCP and others are network active already)
* [x] EDD tables created and configured
* [x] RCP tables created and configured
* [x] Trial created and activated
* [ ] Added to the trial mailing list

**Comment by amdrew** [comment]
The form will live at `/signup` instead of `/register` (though the old form can be seen here for comparison).

The signup page can be accessed via:

1. CTAs on the homepage
2. CTAs on the pricing page
3. The CTA (currently "Start selling") in the site header.

___

The homepage CTA currently asks only for an email address. In the future we could A/B test this with the three fields shown on the signup page.

<img width="785" alt="screen shot 2018-06-07 at 3 09 24 pm" src="https://user-images.githubusercontent.com/52581/41076410-9883d8e2-6a65-11e8-9206-41d68138b1df.png">

___

After entering your email address... (it's possible to skip) ...

<img width="829" alt="screen shot 2018-06-07 at 3 14 24 pm" src="https://user-images.githubusercontent.com/52581/41076417-9f2ca02a-6a65-11e8-9d11-3ed4d53fefd4.png">

___

You arrive on the signup form with the fields outlined in this issue. The email address from the previous step is auto populated. The password field is then auto focused.

<img width="784" alt="screen shot 2018-06-07 at 3 14 45 pm" src="https://user-images.githubusercontent.com/52581/41076423-a7652532-6a65-11e8-8c94-d73b7edd1c32.png">

Other notes:

- It's currently possible to skip the email address on the homepage (though we could enforce it), and if so, the email address field would instead be focused on the signup form. This would also be true if the user arrives on this page from the header or pricing CTA(s).

- The form at `/signup` will need parsley validation, including checking the store name field. If a store name is taken, a message will show. If spaces are entered, they will be treated as hyphens for the store creation. E.g. My Cool Store will create a site of my-cool-store.sellbird.com

- The SellBird logo (this will be replaced with the final logo) on the signup form _is_ clickable, so it's possible to get back to the site by clicking it. This signup page is purposely designed to have minimal distractions for obvious reasons.

- After completing the signup form, it will create a new store and log the user into the dashboard. Here we will show an on-boarding wizard or such.

@DrewAPicture Let me know if you have any thoughts. Feel free to start adding validation, etc.

**Comment by amdrew** [comment]
PR: https://github.com/SellBirdHQ/theme/pull/246

**Comment by amdrew** [comment]
To test, create a page locally with the slug of `signup`.

**Comment by amdrew** [comment]
Pushed the new `page-signup.php` template to master.

**Comment by amdrew** [comment]
@DrewAPicture Looking good so far.

1. After completing the form and arriving in the dashboard, if I click into the `customers` page I get:

```
WordPress database error Table 'sellbird.wp_19_edd_customers' doesn't exist for query SELECT  wp_19_edd_customers.* FROM wp_19_edd_customers    ORDER BY wp_19_edd_customers.id DESC LIMIT 20 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/sellbird/page-dashboard.php'), SellBird\Util\Template->get_template, get_template_part, locate_template, load_template, require('/themes/sellbird/template-parts/dashboard/customers.php'), SellBird\Util\Customers->has_customers, SellBird\Util\Customers->get_customers, EDD_DB_Customers->get_customers, EDD_Customer_Query->query, EDD_Customer_Query->get_items, EDD_Customer_Query->query_items
```

I noticed that the `wp_19_edd_customers` (and `wp_19_customermeta`) DB tables were only created once I visited the newly created site from within the admin (as the network administrator).

2. The form seems to have lost its autofocus for the store name field. If the email address is already entered from the input field on the homepage, then arriving on the signup form should focus on the store name field, rather than the email address field.

3. I'll work on validation styling.

**Comment by amdrew** [comment]
Validation styling added.

**Comment by DrewAPicture** [comment]
The validation is still being written. We have to send off some Ajax requests to make that work, but the only the base JS is in there currently. As for the store name vs slug, that makes sense.

**Comment by amdrew** [comment]
👍 Was just referring to the store name bit

**Comment by DrewAPicture** [comment]
The validation is in place and integrated with Parsley. It only validates on form submission, mostly because shooting off an Ajax request on keyup is a great way to unintentionally overload our server with requests.

**Comment by DrewAPicture** [comment]
I ended up applying the `parsley-error` styles to `parsley-errors-list li` to cover the cases where validator-specific error messages are displayed.

**Comment by DrewAPicture** [comment]
Worth noting that anyone testing this needs to upgrade their local version of EDD to 3.0 (EDD on the `release/3.0` branch) and upgrade their tables. It's expected that you'll still see some EDD database errors in the logs for the ordermeta table and the `date_modified` column in the customers table. These are EDD 3.0 known issues.

**Comment by amdrew** [comment]
@DrewAPicture 

Validation works great from what I can see. Still an issue with the autofocus if entering an email address from the home page.

As mentioned on Slack I really feel we should remove `e.g. *.sellbird.com` from underneath the store name field.

1. It's not something I saw while researching other simple registration forms. I believe there are good reasons why, most likely the below.

1. We're asking the user for a store name (not a URL), so the `e.g. *.sellbird.com` line is technically incorrect. It implies (as from the example) that the user should enter a slug (as denoted by the asterisk), followed by `.sellbird.com`.

    Given that example, a user may try to follow it. If they do and type `my-site.sellbird.com` it would cause the preview to be updated and show `e.g. my-site.sellbird.com.sellbird.com`.

    We want a user to enter something like `My site`. When they type that and look at the preview, it may also be confusing that it shows `my-site.sellbird.com`.

1. It will be possible on specific pricing plans to map your own domain. If a user came to sign up and saw the preview with `.sellbird.com` in the URL, they might be scared off, thinking that's their only option.

1. The preview has a couple of small issues. If you type a store name and then clear it out, the example line updates to `e.g. .sellbird.com` (missing the asterisk as shown originally). 

    It also allows non valid characters to be entered making a URL preview inaccurate. `e.g. my#$@#(@#$@#$(*#$cool-!store.sellbird.com`
 
1. We want the form to be as simple as possible. Things that update while typing can be distracting and cause confusion.

It is possible that a user could misspell their store name and have the site set up with an incorrect subdomain name. I think that's a minor concern given the above points. They can change their store name which is easy enough and to change the actual subdomain they can contact support, or sign up again. 

The other day I signed up to a popular service and it didn't ask me for a store name. It generated my new site using my first name, and then appended a `4` since there was obviously another andrew already: `andrew4.site.com`

**Comment by DrewAPicture** [comment]
@amdrew I believe I've fixed the autofocus issue with the email address as well as removed the URL preview JS. Could you please retest?

**Comment by amdrew** [comment]
@DrewAPicture made some tweaks:

1. The autofocus wasn't quite working, it needed to also be on the store name field. When the user enters an email address from the homepage and arrives on the sign up form (or the email exists in the URL), it should autofocus to the store name field since the email is already populated. 

   Instead of `false` in the ternary statements, I changed it to `''` so it only gets outputted in the HTML when it is true. When it exists in the HTML as false, it prevents the autofocus working on the other field. 

    - [x] If no email is specified, autofocus on the `Your email address` field.
    - [x] If email is specified (either from the homepage, or in the URL), autofocus on the `Your store name` field.

2. Removed the `e.g. *.sellbird.com` from the store name field
3. Removed the autofocus from the password field. We only need it on the first 2 fields.
4. Fixed the validation message on the store name field, was showing the default validation message due to a small typo
5. Removed the `#name-error` div from the HTML. Seems to work fine without it. Do we still need it for something?

**Comment by amdrew** [comment]
Couple more things:


1. When I entered an email address that already exists, it correctly showed the notice about the email already existing. However when attempting to change the email address to something unique,  the validation is firing ajax requests for every keystroke making it very difficult to enter a new email address since there's lag between each character entered.

    <img width="1111" alt="screen shot 2018-08-20 at 1 33 29 pm" src="https://user-images.githubusercontent.com/52581/44316069-ae7b8d00-a47d-11e8-9027-4f6f204d46ad.png">

    The login link in the validation line also needs to go to /login

2. I have an existing store with a slug of `sumobi11`. When entering `Sumobi11` as the store name at signup and submitting I get multiple instances of each error below:

```
PHP Notice:  Object of class WP_Error could not be converted to int in /wp-includes/ms-blogs.php on line 816
```

```
PHP Warning:  trim() expects parameter 1 to be string, object given in /wp-includes/ms-blogs.php on line 83
```

```
PHP Warning:  Cannot modify header information - headers already sent by (output started at /wp-includes/ms-blogs.php:816) in /wp-includes/pluggable.php on line 920
```

Because of the errors above it switches the active theme from SellBird to Twenty Sixteen.

Tested again with a different store name that doesn't exist and it created the site ok.

**Comment by DrewAPicture** [comment]
After some experimentation, I've managed to override the use of the `input` event via setting the `parsley-trigger-after-error` to `focusout` instead.

**Comment by DrewAPicture** [comment]
Reopening this to serve as a tracking ticket for a few outliers not necessarily related to the process of creating the site.

**Comment by DrewAPicture** [comment]
@amdrew On the "Added to the trial mailing list" item, what did you have in mind there, or is that something we can handle in a separate issue?

**Comment by amdrew** [comment]
@DrewAPicture I can't quite recall. But I'm going to guess it's related to adding any trial customers to a mailing list segment so we can more easily send them targeted emails. Welcome to your trial, your trial is ending etc, last chance etc

**Comment by DrewAPicture** [comment]
@amdrew Ok, can you create a separate issue so we can close this one m
