### ISSUE TITLE
Indicate logged-in user in the header (avatar/log out link)

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#25]
Right now there isn't really a way to tell what user you're logged in as, nor that you're logged in as a member of a store (other than that you can see the dashboard and not the coming soon page). Also, we hide the admin bar for store owners so we don't even have that.

Could we get some kind of ubiquitous avatar + log out link in the header?

**Comment by DrewAPicture** [comment]
Current header:

![header](https://cl.ly/0U2s3P04351h/Screen%20Shot%202017-08-15%20at%2012.49.14%20PM.png)

**Comment by pippinsplugins** [comment]
I'd definitely like to show something similar to the WP tool bar but specific to SellBird.

**Comment by amdrew** [comment]
Agreed, briefly mentioned something similar on https://trello.com/c/BWlr5liB/24-mvp

**Comment by amdrew** [comment]
The profile section in the dashboard header has been greatly improved. Previously it was just the user name and user's gravatar. 

It now shows the store name underneath the user's name, has a hover effect, and when clicked it will open a dropdown menu. The links are not finalized, but at the very least it will include a link to log out.

Default state:

<img width="336" alt="screen shot 2018-04-03 at 1 37 18 pm" src="https://user-images.githubusercontent.com/52581/38224489-65ba4fda-3744-11e8-90f4-e1b5ceb704b0.png">

When clicked:

<img width="342" alt="screen shot 2018-04-03 at 1 37 31 pm" src="https://user-images.githubusercontent.com/52581/38224488-658bd894-3744-11e8-8e17-36de0b8da419.png">

We will need to:

- [ ] Show this user profile menu at mobile resolutions. We can either include it to the right of the mobile menu, or included within the mobile menu itself. See https://github.com/SellBirdHQ/theme/issues/130#issuecomment-378099712
- [ ] Finalize what we need in the dropdown menu, in addition to the log out link.

**Comment by amdrew** [comment]
3 new links have been added to the mobile menu:

View Store
Your Profile
Log Out

<img width="397" alt="screen shot 2018-05-22 at 2 27 03 pm" src="https://user-images.githubusercontent.com/52581/40338986-40eff25a-5dcc-11e8-9adc-99b06a69689e.png">

And with that, this issue can be closed.
