### ISSUE TITLE
Rename "Managers" to "Staff"

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#252]
As @DrewAPicture has mentioned before, "Managers" was something he decided upon at the time and suggested we change it if something else made more sense.

Managers doesn't work very well because as the original store owner, you _are_ the manager. You don't want to add more managers.

I propose we change to "Staff". The store owner would then add new staff accounts to assist with the store.

**Comment by DrewAPicture** [comment]
Hmm. I don't know about Staff either. I think it implies that those are people who are going to be providing some kind of customer service vs Managers who would be doing management (store not people). At this point I still feel like Managers is the best option.

**Comment by amdrew** [comment]
How about just "Users"?

You could add a new user and then decide what type/role of user they are, or assign permissions. Would be easier just to have predefined types. Add another "owner", add a "store manager" etc.

**Comment by amdrew** [comment]
After further discussion we're going to hold off on the "Managers" screen for now. This can be re-introduced at a later date.
