### ISSUE TITLE
Show a preview link for About and Contact pages in the Settings screen

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#253]
#239 implemented editing of the About and Contact Us pages, and @amdrew suggested we link to the previews from there as well.

**Comment by DrewAPicture** [comment]
@amdrew I started a PR which adds the links but I'm gonna need a little bit of help with the styling/positioning of them. I was setting them up to be on the same line with the legends for the fieldsets, except fieldsets are full-width, block level so I guess that's not going to work.

In #239, I was initially just displaying the legends for screen readers only, but eventually showed them once the scrolling mechanism was added. Be careful with rearranging anything outside of the `div id="*-settings">` divs as they're tied to the scrolling nav.

**Comment by DrewAPicture** [comment]
![Preview links[(http://mr.drewf.us/1D0v2T3v0I0W/Screen%20Shot%202018-06-18%20at%201.12.45%20AM.png)

**Comment by DrewAPicture** [comment]
![Preview links](http://mr.drewf.us/1D0v2T3v0I0W/Screen%20Shot%202018-06-18%20at%201.12.45%20AM.png)

**Comment by amdrew** [comment]
👍 Will take a look

**Comment by amdrew** [comment]
@DrewAPicture Thoughts on using a radio group for the show/hide?

**Comment by amdrew** [comment]
Otherwise ready for a review

**Comment by DrewAPicture** [comment]
@amdrew Thanks for fixing that up!
