### ISSUE TITLE
"Discount successfully deleted" notice not dismissed automatically

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#260]
The `Discount successfully deleted` notice isn't dismissed automatically like other notices.

<img width="378" alt="screen shot 2018-06-21 at 10 58 05 am" src="https://user-images.githubusercontent.com/52581/41688878-fe30035a-7541-11e8-8af2-678d82727ae5.png">

**Comment by DrewAPicture** [comment]
PR: #267

**Comment by amdrew** [comment]
All fixed, merged.
