### ISSUE TITLE
Set page template for products page on site creation

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#285]
When creating a new site, we create a products page and place the `[downloads]` shortcode on it. It would be more flexible (at least for now) if we instead set a page template which has the call to the shortcode on it, rather than setting it in the post content.

According to `wp_insert_post` (https://developer.wordpress.org/reference/functions/wp_insert_post/#notes), you should be able to pass `page_template` with the template path though for some reason I could not get this working. 

I opted to set the page template with `update_post_meta` instead.

**Comment by amdrew** [comment]
PR: https://github.com/SellBirdHQ/theme/pull/286

The template has already been included in the store theme.

**Comment by DrewAPicture** [comment]
Rather than creating a page and setting the template we should just create a page-products.php template and kill two birds with one stone.

**Comment by amdrew** [comment]
For future-proofing a page template would be better as the page may not always have a slug of "products".

E.g. for a site that sells stock photography, `/products` isn't great. `/photos` or `/store` seem a lot better.

**Comment by DrewAPicture** [comment]
Which page template value are you passing in the `page_template` argument for `wp_insert_post()`? `products.php`?

**Comment by DrewAPicture** [comment]
I'm asking only because I don't see any page templates other than Pricing in the theme folder. The template has to exist in the array returned from `get_page_templates()` and it has to be the full relative path from the theme root. So if we were citing the pricing template, the passed value would need to be "page-templates/pricing.php".

**Comment by DrewAPicture** [comment]
OIC, nvm. You're citing a template in the store theme.

**Comment by DrewAPicture** [comment]
Looked into this a little deeper last week and related what I found in Slack but forgot to update here.

> So yeah, classic race condition on the page template issue. The pages and theme menu is setup long before the theme is actually activated, so the pages templates array is empty at the point where the products page is created.
>
> Since we're storing the pages in a property in `setup_pages()` for the benefit of `custom_menu()`, we can reuse those values to just set the page template at the end of `activate_site()`.
>
> Technically speaking, the way you have it setup works because it's blindly setting the page template even before WordPress recognizes the template as existing.

**Comment by spencerfinnell** [comment]
Check out: https://dev.bigboxwc.com/automatically-apply-custom-page-templates/

I've really been liking this technique lately as you can automatically apply a "template" without it having been officially registered. You avoid stuffing the Page Templates dropdown with one time use templates and instead can keep it for actual layout templates.

**Comment by amdrew** [comment]
New PR (more or less the same) https://github.com/SellBirdHQ/theme/pull/309

@spencerfinnell Just getting back to this issue again. I saw the link you posted originally but now it's showing a 404. Any chance of getting that live again so I can take another look? Cheers.

**Comment by spencerfinnell** [comment]
@amdrew -- oops.

Here is the relevant gist: https://gist.github.com/spencerfinnell/46646f6a98dd9e01ab365734fc895024

**Comment by spencerfinnell** [comment]
Article is back up: https://dev.bigboxwc.com/automatically-apply-custom-page-templates/

**Comment by amdrew** [comment]
@spencerfinnell Thanks 👍

**Comment by amdrew** [comment]
@spencerfinnell That's dope, just implemented it
