### ISSUE TITLE
New sites not created with same protocol

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#303]
When I create a new site via the registration form, any new site is created as `http`, not `https` like my main site on the network. Pretty sure this isn't something on my end?

<img width="625" alt="screen shot 2018-09-13 at 2 21 45 pm" src="https://user-images.githubusercontent.com/52581/45464163-6e998400-b763-11e8-9865-f4fe944bf693.png">

<img width="618" alt="screen shot 2018-09-13 at 2 45 20 pm" src="https://user-images.githubusercontent.com/52581/45464210-a9032100-b763-11e8-80b5-7dfbcae190c1.png">

**Comment by DrewAPicture** [comment]
I'm pretty sure this is an RCP Site Creation bug.

**Comment by DrewAPicture** [comment]
The PR for RCP Site Creation has been merged to latest `master`.

**Comment by amdrew** [comment]
Can confirm this works now 👍
