### ISSUE TITLE
Dashboard > Managers

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#31]
Add a panel for adding and managing store user "Managers".

**Comment by DrewAPicture** [comment]
PR: #32

This only adds the shortcode, and basic listing logic. Adding new managers will be in a separate PR.

**Comment by DrewAPicture** [comment]
![Managers](https://cl.ly/1c342A0f1d3y/Screen%20Shot%202017-08-27%20at%2010.06.20%20AM.png)

**Comment by pippinsplugins** [comment]
Great idea and PR looks good, merged.

**Comment by DrewAPicture** [comment]
Add was also shored up Managers > New with b7cb3a0a50f4560c6c4ee34673c4e7bff9df7bf7, 513c7ceda8166c48eef7829c26d75cb2bf2382ae, and b7b28d08073b05e574024e7b65ef2ea62f56f9f3. The basics here are done. Let's revisit in other issues.
