### ISSUE TITLE
Managers cannot access dashboard pages

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#33]
Store managers cannot access any of the dashboard pages. When attempting to view the pages, they are redirected to the homepage.

**Comment by DrewAPicture** [comment]
Can you outline the steps you used to test? It worked fine for me when I switched to the blog user and visited the dashboard on the primary site.

**Comment by DrewAPicture** [comment]
For instance, here are my testing steps on the live site:

1. Navigate Network Admin > Users
2. Switch to the stripe2 user
3. Visit Dashboard > Settings to confirm I'm associated with the Stripe2 site
4. Visit Dashboard > Managers
5. Create a new manager, `stripe2-manager`
6. Switch back to my admin account via sellbird.com/wp-login.php
7. Navigate to stripe2.sellbird.com/wp-admin/users.php
8. Switch to the `stripe2-manager` account
9. Navigate back to the sellbird.com Dashboard and view any page

Now, granted, we'll eventually want to lock this down a little bit (only allowing the store owner, for instance, to manage the managers), but this the above steps worked as expected.

**Comment by pippinsplugins** [comment]
That's exactly what I did and I could never view the dashboard.

Could you try it on sellbird.com with my "managertest" account I created?

**Comment by DrewAPicture** [comment]
In short, managers are created as users of the subsite they belong to _only_. It gets a little more complicated if you try to test with a super admin that is a member of multiple sites because any one user can only belong to one site as far as RCP site creation is concerned.

**Comment by pippinsplugins** [comment]
False alarm! This was due to my IP address changing. The maintenance mode plugin was kicking me out.

@amdrew I bet this is why you couldn't access the dashboard last week.
