### ISSUE TITLE
Provide helper function for is_manager()

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#34]
It will be very useful to have a helper function for `is_manager()` that can be called from the global scope. For example, we're using the Menu Items Visibility plugin to control what menu items are shown. Menu items like `Billing` should not be shown, as an example.

It's likely we'll hard code the menu items in template files but this will still be useful.

**Comment by DrewAPicture** [comment]
I'm confused about the "global scope" part. If the user is logged-in, there isn't exactly a "global scope" because they're logged-in to their site and viewing the dashboard because we've switched to their store. So do you mean is_manager() in the scope of when the user is store-switched?

**Comment by pippinsplugins** [comment]
I just mean that we need to be able to call the function from the global scope so that it can be used in contexts like the Menu Item Visibility plugin.

**Comment by DrewAPicture** [comment]
@pippinsplugins I've added a helper in 1e569ca7ad3825a1d7bca62cf87cf4254829c930. In testing the Menu Item Visibility Control plugin, I noticed that to use namespaces, you have to escape the backslashes, e.g.
```
! ( new \\SellBird\\Util\\Store )->is_manager()
```

If you're thinking, "that's convoluted", remember that everything is under the `SellBird` namespace regardless, so even if we move it up a level, it's still gonna have to be entered as `\\SellBird\is_manager()`, which we can still do if you like.

**Comment by DrewAPicture** [comment]
See 616ed2fca779ba5a1a4ff48a44d4769bfc7cec6d for the introduction of `\SellBird\is_manager()`.

**Comment by DrewAPicture** [comment]
See 616ed2fca779ba5a1a4ff48a44d4769bfc7cec6d for where I've also added `\SellBird\is_manager()`, which is simply a wrapper for the more verbose version.

**Comment by pippinsplugins** [comment]
I have no issues with the convolution!
