### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SellBird\Bootstrap\Scripts' not found

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#38]
The `Orders` page on the live site is blank, presumably from this fatal error which I can see locally.

```
Fatal error: Uncaught Error: Class 'SellBird\Bootstrap\Scripts' not found in /wp-content/themes/sellbird/template-parts/dashboard-orders.php on line 14
```

**Comment by amdrew** [comment]
Still seeing this error locally, you can view it on the site also: http://sellbird.com/dashboard/orders/

**Comment by DrewAPicture** [comment]
Yeah, that's my fault. The class got renamed to `Assets` :D
