### ISSUE TITLE
JS errors around dashboard when SCRIPT_DEBUG is set to false

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#43]
There's some JS errors popping up around the dashboard with `SCRIPT_DEBUG` set to `false`

On `/dashboard/products/`, `dashboard/settings/`, `/dashboard/customers/`:
`TypeError: context is null from Chart.bundle.js:10083:1`

^ Probably because when script debug is false it loads the minified JS file that contains everything, and perhaps the chart HTML doesn't exist:
https://github.com/SellBirdHQ/theme/blob/master/includes/bootstrap/class-assets.php#L126

On `/dashboard/`

`TypeError: sellbird.image is undefined`

**Comment by DrewAPicture** [comment]
Just leaving a note here that JS errors stemming from the minified script getting enqueued is a known issue.

**Comment by DrewAPicture** [comment]
Not seeing any errors on /dashbord after re-minification in c3ab7cba4569ce971dd589d5818eae7958d02db3, but it's definitely come up before, so we should leave this open until any known stuff is resolved.

**Comment by DrewAPicture** [comment]
@amdrew Can you please test with #47 to check to see if you're still getting that TypeError?

**Comment by amdrew** [comment]
@DrewAPicture The first TypeError is now gone, the second still exists on `/dashboard`.

**Comment by DrewAPicture** [comment]
This issue will be fixed as part of the PR for #90. See https://github.com/SellBirdHQ/theme/pull/92/commits/eb1b71c4663586337d5aabac8aea63cd15059a5c
