### ISSUE TITLE
Store name needs unslashed on render

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#56]
<img width="1021" alt="screen shot 2017-09-12 at 12 59 12 pm" src="https://user-images.githubusercontent.com/1034109/30341034-3457cf14-97ba-11e7-98f5-f6d774fc61f0.png">

**Comment by DrewAPicture** [comment]
With PR #57:

![Unslashed](https://cl.ly/3x2U222F230d/Screen%20Shot%202017-09-12%20at%2012.17.45%20PM.png)
