### ISSUE TITLE
Set up default pages on registration

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#58]
When a user registers, there should be some pages that are auto-created for their site.

Based off https://trello.com/c/BWlr5liB/24-mvp these pages _could_ be:

**Products**
This could be set to be the static front page and show a faux product grid initially as per https://github.com/SellBirdHQ/theme-store/issues/4

**About**
Because providing some information about your company is a good idea.

**Contact**
Perhaps we set up a basic form?

The other option is to let the user create these pages from the dashboard. Both options would require letting the user edit the basic contents of the page (title, text etc)

@pippinsplugins @DrewAPicture Keen to hear your thoughts

**Comment by pippinsplugins** [comment]
Those all sound right to me and I don't think there are any others we need to include at this time.

**Comment by DrewAPicture** [comment]
FWIW, we already set up a "Home" page containing the `[downloads]` shortcode and set it as the page on front when a new member is activated.

**Comment by DrewAPicture** [comment]
The code for that is in the `Registration` class, so feel free to modify as necessary :-)

**Comment by amdrew** [comment]
👍 Will do

**Comment by amdrew** [comment]
@DrewAPicture Just registered a new site, not seeing the "home" page with the [downloads] shortcode or any page set as home.

<img width="403" alt="screenshot 2017-09-21 14 56 24" src="https://user-images.githubusercontent.com/52581/30676993-37a507d4-9edd-11e7-9c6a-6896823615b1.png">

<img width="557" alt="screenshot 2017-09-21 14 56 29" src="https://user-images.githubusercontent.com/52581/30676994-37a554e6-9edd-11e7-9b27-757f226377d5.png">

@DrewAPicture @pippinsplugins We're going to need a form plugin pre-installed on sign up, and a form outputted to the contact page with some basic fields. Any suggestions on the plugin? (Gravity Forms etc). 

In the future we'd ideally provide a way for users to view their submissions from their dashboard.

**Comment by pippinsplugins** [comment]
I think Gravity Forms. It has the best front end entry management I'm aware
of.

**Comment by amdrew** [comment]
+1

**Comment by amdrew** [comment]
@DrewAPicture Got everything set up locally. After registering, the home page _did_ get created with the `[downloads]` shortcode and assigned to the front page. So something up with the live site.

**Comment by amdrew** [comment]
How do we want to handle the editing of a page, i.e. the about page? 

Do we simply show an input field and textarea for the about page's title and page body? 

And for the contact page do we show an email field for the contact form? If no information is entered for either page, we could hide the page altogether. Seems like the simplest option for now.

**Comment by pippinsplugins** [comment]
I think a set of simple input fields would suffice. I imagine those could live in the `Settings` tab of the dashboard page.

The contact form really doesn't need any setting beyond an email address. For 1.0, that could just be the account email. If any settings, maybe a "Enable contact form" toggle just so some people can turn it off if they want.

**Comment by amdrew** [comment]
Sweet. A textarea will be better than an input field for the actual content of the about page. A checkbox for showing the contact form does seem less confusing than "don't enter an email address to hide the contact form" 👍 

@DrewAPicture Since you're working on the dashboard, could you add the above?

**Comment by amdrew** [comment]
@DrewAPicture PR for you to review: https://github.com/SellBirdHQ/theme/pull/62.

- Your `create_homepage()` method is now a more generic `theme_setup()` method
- I've renamed the "Home" page to "Products" since by default the home page will only be showing products for now. If a customer is on another page such as About, they will then click "Products" to view the store's products.
- 2 new pages are created at registration, "About" and "Contact". These are set to draft (see below)
- A "Main" menu is created and assigned to the primary menu location that Themedd provides. This covers #60
- The About and Contact pages are added to the new menu but set to draft (see below)

**Draft pages and menu items**

I think we should create the additional pages and menu items during the site registration and set them to draft. This allows us to simply pull the default title/content of the draft "About" page onto the dashboard. We could provide 1 sentence of default content inside the text area to help them along.

Enabling the page via a checkbox simply sets the page and the menu item to `publish` (and vice versa if they decide to disable it). This will be the same for the Contact page - once they enter their email address in an input field there could be a checkbox option to enable the contact page.

**Comment by DrewAPicture** [comment]
Merged the PR: #62, which added logic for adding the basic pages and menu to hold them. Using the `menu-item-status` value is clever, nice work @amdrew :-)

**Comment by DrewAPicture** [comment]
Per the scrub discussion yesterday, @amdrew will re-test and figure out if there's anything out standing here.

**Comment by amdrew** [comment]
Retested and everything looks good.

The `About` and `Contact` pages are created as drafts. The `Products` page is created with the `[downloads]` shortcode and set to be the Front Page.

<img width="425" alt="screen shot 2018-05-28 at 4 27 48 pm" src="https://user-images.githubusercontent.com/52581/40597235-4ba757b6-6294-11e8-9175-134e0534f151.png">

The primary menu is also set up with the required pages added:

<img width="567" alt="screen shot 2018-05-28 at 4 27 41 pm" src="https://user-images.githubusercontent.com/52581/40597245-61986cd6-6294-11e8-9585-775d90f20b59.png">

Store currently looks like this upon registration with no products added:

<img width="1460" alt="screen shot 2018-05-28 at 4 30 20 pm" src="https://user-images.githubusercontent.com/52581/40597266-7ece83d0-6294-11e8-809f-e05ff1daec3e.png">

Going to close this issue and will open new issue(s) for remaining tasks discussed above.
