### ISSUE TITLE
Make HTML tables responsive

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#59]
Tables on the dashboard will need to be responsive wherever possible.

**Comment by amdrew** [comment]
Ready for testing, see PR at #184. 

A horizontal scrollbar will appear on tables at smaller resolutions.

**Comment by pippinsplugins** [comment]
@amdrew I'm happy for you to just push these straight into `master` so that they're deployed to the site. Since the site isn't live, it's easiest to test on the live site.

**Comment by amdrew** [comment]
@pippinsplugins 👍 I'll merge and deploy #184 to the live site when I can so it's easier for testing. Before I do, I need to double-check the coming soon page which is live, since I made a lot of changes. Most notable was switching from LESS to SASS, so all CSS has been rewritten.
