### ISSUE TITLE
Adjust Stripe customer creation to enable shared customers

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#77]
Moved to SellBirdHQ/sellbird/issues/29.

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/edd-stripe/issues/276

**Comment by pippinsplugins** [comment]
Stripe gateway updated with the necessary filters.

**Comment by DrewAPicture** [comment]
Moved to SellBirdHQ/sellbird/issues/29.
