### ISSUE TITLE
Undefined variable: output

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#79]
I'm seeing a PHP notice on the Orders page:

NOTICE: wp-content/themes/sellbird/includes/bootstrap/class-notices.php:86 - Undefined variable: output

**Comment by DrewAPicture** [comment]
Ahh yeah. From #8. I'm on it.

**Comment by amdrew** [comment]
Wasn't me. /me runs

**Comment by DrewAPicture** [comment]
@amdrew It _wasn't_ you. I restructured the method before I merged.
