### ISSUE TITLE
Add a generic "Success" notice for a variety of operational redirects

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#8]
We need some kind of visual feedback that settings have been saved now that Dashboard > Settings is saved via Ajax to facilitate logo upload.

**Comment by amdrew** [comment]
👍 Let's just make it a simple `div` with two classes, `notice` + either `notice-success` or `notice-error`. I can make it look pretty. 

Or instead of `notice` we could use `alert`

**Comment by amdrew** [comment]
@DrewAPicture I think this is all we need for now. Want to give it a once over?

Colors are subject to change but here are a couple of examples:

<img width="855" alt="screenshot 2017-10-06 15 51 15" src="https://user-images.githubusercontent.com/52581/31261030-6113e07c-aaae-11e7-8168-bae68e134648.png">

<img width="837" alt="screenshot 2017-10-06 15 50 46" src="https://user-images.githubusercontent.com/52581/31261031-611455f2-aaae-11e7-97dd-8d267dad95ca.png">

**Comment by pippinsplugins** [comment]
Looking good!

**Comment by DrewAPicture** [comment]
Yeah, looks good to me.
