### ISSUE TITLE
Activate the SellBird plugin for new stores

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#81]
The [SellBird](https://github.com/SellBirdHQ/sellbird) plugin is now going to serve as a base functionality plugin for all stores since we moved all of its logic into the sellbird.com theme. Therefore, we need to activate on it all new stores :-)

**Comment by pippinsplugins** [comment]
How about just making it an mu-plugin instead?

**Comment by DrewAPicture** [comment]
@pippinsplugins It realistically shouldn't be running on the main site because we'll be setting filters on charges generated by edd-stripe that add application fees, and otherwise manipulating EDD to do store-specific things that could realistically wreak havoc on how the main site operates.

**Comment by DrewAPicture** [comment]
Started a PR (WIP): #83

**Comment by DrewAPicture** [comment]
But we could try a mu-plugin, maybe bailing early if on the main site or something.

**Comment by DrewAPicture** [comment]
OK, I've set it up successfully as a mu-plugin.

To run it on local, you'll need to check out a copy of https://github.com/SellBirdHQ/sellbird into your wp-content/mu-plugins directory (the folder it lives in must be called `sellbird`).

In order for WordPress to load the plugin via the directory, you'll also need to create a file (on the server it's called `sellbird-store.php` containing the following:

```php
<?php
/**
 * Plugin Name: SellBird Store
 * Description: Provides all custom functionality for SellBird store fronts
 * Version: 1.0.0
 * Author: Sandhills Development, LLC
 */

if ( stream_resolve_include_path( __DIR__ . '/sellbird/sellbird.php' ) ) {
	require_once __DIR__ . '/sellbird/sellbird.php';
}
```

**Comment by DrewAPicture** [comment]
`mu-plugins/sellbird/` – Contains the plugin
`mu-plugins/sellbird-store.php` – Loads the plugin.

**Comment by pippinsplugins** [comment]
Having it load on the main site shouldn't be an issue simply because the main site won't actually use EDD for anything.
