### ISSUE TITLE
Order ID missing from orders overview

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#82]
The ID of orders is not being shown in the table:
<img width="828" alt="screen shot 2017-10-11 at 9 18 00 pm" src="https://user-images.githubusercontent.com/1034109/31476012-b2f47ab8-aec9-11e7-95c5-824b00a63f79.png">

Looks like this is also making the View link not work because there is no ID in the URL either.

**Comment by DrewAPicture** [comment]
I think the problem might be that you're testing with an account that is associated with multiple stores. Try switching to a single-store account. RCP Site Creation currently only supports a 1:1 relationship of user/manager:site (meta key holds only one ID).

**Comment by DrewAPicture** [comment]
Hmm, looks like the '_edd_payment_number' value isn't set for the order that's being displayed.

**Comment by DrewAPicture** [comment]
Is it possible that the objects returned from `edd_get_payments()` aren't prepared the same way as directly retrieving a single payment by post ID?

**Comment by DrewAPicture** [comment]
Is there anything you can think of that would normally prevent the meta key from being set when a payment is created? Can we rely on the `_edd_payment_number` meta value being set?

**Comment by pippinsplugins** [comment]
`_edd_payment_number` won't be reliable, instead use `$payment->number`.

`_edd_payment_number` is used to store a customer sequential order number for the payment. `number` is a property that retrieves the sequential number if present or the unique DB ID if it is not. The `number` property is set up like this:

```php
/**
 * Setup the payment number
 *
 * @since  2.5
 * @return int|string Integer by default, or string if sequential order numbers is enabled
 */
private function setup_payment_number() {
	$number = $this->ID;

	if ( edd_get_option( 'enable_sequential' ) ) {

		$number = $this->get_meta( '_edd_payment_number', true );

		if ( ! $number ) {

			$number = $this->ID;

		}

	}

	return $number;
}
```

**Comment by pippinsplugins** [comment]
That did it!
