### ISSUE TITLE
Allow store owners to create discount codes

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#84]
Store owners should be able to create discount codes. These discount codes should include the following options:

- flat or percentage
- amount of discount
- expiration date
- start date
- max uses

These are all features EDD discounts already support.

**Comment by DrewAPicture** [comment]
WIP PR: #122

**Comment by DrewAPicture** [comment]
Merged the initial PR, #122. Here's the checklist for what's completed and still needed:

* [x] Discounts (list)
* [x] Discount > Add (template + saving + notice)
* [x] Discount > Edit (template + saving + notice)
* [x] Discount > Delete (template + deleting + notice)
* [x] Utility class
* [x] Registered routes
* [ ] Datepickers for start date and expiration
* [ ] Max uses for edit and add + saving
* [ ] Enabled products UI + saving
* [ ] Disabled products UI + saving

**Comment by DrewAPicture** [comment]
Started a new PR to add the additional settings: #197

**Comment by pippinsplugins** [comment]
@DrewAPicture I don't see the discounts option:
<img width="542" alt="screen shot 2018-05-03 at 10 20 02 am" src="https://user-images.githubusercontent.com/1034109/39585972-966f6924-4ebb-11e8-80e8-2a2816518736.png">

**Comment by DrewAPicture** [comment]
You have to add it to your menu.

**Comment by pippinsplugins** [comment]
@DrewAPicture got it!

Note, in the future please go ahead and make any changes to the live sellbird.com site that are necessary when merging changes into `master`. All changes are auto-deployed and to ensure testing results show as expected, menu / page changes should be done at the same time.

Thanks!

**Comment by DrewAPicture** [comment]
Honestly, I'd forgotten that sellbird.com was attached to `master`, so noted.
