### ISSUE TITLE
Product Prices: Repeatable row JS for Products > Add/Edit

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#87]
Master checklist: #44 

For this issue we need to add repeatable row JS for variable prices when adding and editing products. This encompasses only the JS aspect of adding new (valid) fields in sequence for variable pricing as well as removing prices.

This also covers dynamically updating the variable prices list for use by download repeatable fields.

**Comment by DrewAPicture** [comment]
WIP PR: #106

**Comment by DrewAPicture** [comment]
Reopening with a new WIP PR to implement dynamic pricing for files.

**Comment by DrewAPicture** [comment]
New WIP PR: #107

**Comment by DrewAPicture** [comment]
Merged #107.

**Comment by pippinsplugins** [comment]
@DrewAPicture Looks like the price assignment drop down is not getting populated with newly added price options until after save.

After saving it looks good:
<img width="802" alt="screen shot 2017-11-02 at 9 16 05 am" src="https://user-images.githubusercontent.com/1034109/32330626-aa2ee5f8-bfae-11e7-9c4b-02aac473a273.png">

Pre-saving it's just a blank dropdown.

**Comment by DrewAPicture** [comment]
See the gif I posted in Slack. Are you getting an JS errors? Cause it works on the live site on both product add and product edit.

**Comment by pippinsplugins** [comment]
@DrewAPicture It's working fine for me now actually. I think I might have thought it was failing because I didn't enter price names after adding the prices, so there was no value to display in the dropdown.
