### ISSUE TITLE
New proposed UI

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#96]
We should flesh out a better/more intuitive UI for v1.0. 

1. We're currently loading all of the site's assets (CSS, JS) for the customer, who is there to manage their products. The dashboard should have its own assets, and those assets only to provide an experience as fast as possible. 

    It also limits our creativity when styling elements since we are styling with what is already available within the theme. The styling of the actual site's buttons for example is likely to be different than the buttons of the dashboard. If we keep it as-is, we're forced to change all buttons to be the same, or add more CSS to provide new button styling, further bloating the stylesheet.

2. Likewise with HTML. The new UI should load a basic sidebar on the left (everything in our current menu) and the page content on the right. Everything else the theme loads should be nuked. Would make it much easier to work with also, since any change to the dashboard CSS will only affect the dashboard, and not our actual site used for marketing.

This issue would encapsulate these other issues:
https://github.com/SellBirdHQ/theme/issues/25
https://github.com/SellBirdHQ/theme/issues/65

**Comment by DrewAPicture** [comment]
Awesome!

**Comment by amdrew** [comment]
@DrewAPicture Where do you think we should chuck all these dashboard-related functions? `includes\dashboard\functions.php` or similar?

**Comment by DrewAPicture** [comment]
Add them as methods under the Util\Template class.

**Comment by amdrew** [comment]
This was merged into master
